development:
  adapter: postgresql
  database: dev_panpan
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: test_panpan
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db_panpan
  pool: 5
  timeout: 5000